# Rename this file to languages.toml to enable multilingual support

[zh-cn]
disabled = false
languageName = "简体中文"
languagedirection = "ltr"
title = "Romeo Ahmed 的博客"
weight = 1

[en]
disabled = false
languageName = "English"
languagedirection = "ltr"
title = "Romeo Ahmed's Blog"
weight = 2
