[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/romeoahmed"

[social.params]
icon = "brand-github"

[[social]]
identifier = "gmail"
name = "Gmail"
url = "mailto:ahmedorqwn@gmail.com"

[social.params]
icon = "brand-gmail"

[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/355572423"

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "rss"

# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"

# [social.params]
# icon = "brand-twitter"
